site_name: MARS

site_url: https://marstmu.com/
site_description: MARS Documentation.
site_author: Zeul
repo_url: https://github.com/zeulewan/marswebsite
edit_uri: blob/master/docs/

theme:
  palette:
    primary: black
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: img/logo-no-text.png
  favicon: img/favicon.ico
  features:
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - search.suggest
    - navigation.instant
    - content.action.edit
    - content.code.copy
    - navigation.indexes
plugins:
  - blog
  - search

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - md_in_html
  - tables


  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  
extra_css:
  - css/extra.css