site_name: MARS

site_url: https://marstmu.com/
site_description: MARS Documentation.
site_author: Zeul
repo_url: https://github.com/zeulewan/marswebsite
edit_uri: blob/master/docs/

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: img/logo-no-text.png
  favicon: img/favicon.ico
  features:
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - navigation.instant
    - navigation.path
    - content.action.edit
    - content.code.copy
plugins:
  - blog:
      enabled: false
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  
extra_css:
  - css/extra.css