site_name: MARS

site_url: https://marstmu.com/
site_description: Project documentation with Markdown.
site_author: Zeul
repo_url: https://github.com/zeulewan/test
edit_uri: blob/master/docs/

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: img/logo-no-text.png
  favicon: img/favicon.ico
  features:
    - navigation.sections
    - navigation.tabs



extra_css:
  - css/extra.css