site_name: MARS

site_url: https://marstmu.com/
site_description: MARS Documentation.
site_author: Zeul
repo_url: https://github.com/zeulewan/marswebsite
edit_uri: blob/master/docs/

theme:
  name: material
  #custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  logo: img/logo-no-text.png
  favicon: img/favicon.ico
  features:
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - search.suggest
    - navigation.instant
    - content.action.edit
    - content.code.copy
    - navigation.indexes
plugins:
  - blog
  - search

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  
extra_css:
  - css/extra.css