authors:
  zeul:
    name: Zeul Mordasiewicz
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/55005377
    url: https://github.com/zeulewan
  kolya:
    name: Nikolai
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/145951024
    url: https://github.com/nikolaisydorenko 